const LABS = [
  {
    id: 1,
    title: 'Chained IDOR — Account Takeover',
    slug: 'chained-idor',
    appName: 'NexaPay Digital Bank',
    port: 9001,
    difficulty: 'Intermediate',
    category: 'Broken Access Control',
    estimatedTime: '30–45 min',
    description: 'NexaPay is a modern digital banking platform offering personal and business accounts. The application exposes a RESTful API for account management and fund transfers. However, several API endpoints have inconsistent access control enforcement, and sensitive tokens are exposed in account records.',
    objective: 'Transfer funds from another customer\'s account into your own by discovering and chaining multiple access control flaws. The flag is revealed when your balance exceeds $10,000.',
    hints: [
      'Production APIs often have more endpoints than the UI exposes. Look for documentation links.',
      'HTTP response headers frequently contain metadata about available API resources.',
      'Account detail endpoints may expose internal fields that are not rendered in the UI.',
      'Transfer operations sometimes rely on bearer tokens that are stored alongside account data.',
    ],
    credentials: 'customer1 / password123',
    flag: 'VBANK{ch41n3d_1d0r_t0_4cc0unt_t4k30v3r}',
  },
  {
    id: 2,
    title: 'Broken Function-Level Authorization',
    slug: 'broken-function-auth',
    appName: 'FinVault Admin Portal',
    port: 9002,
    difficulty: 'Intermediate',
    category: 'Broken Access Control',
    estimatedTime: '30–45 min',
    description: 'FinVault is a financial administration portal used by analysts and administrators. The web UI correctly hides administrative functions from low-privilege users, but the underlying API may not enforce the same restrictions.',
    objective: 'Escalate your privileges from "analyst" to "administrator" and access the admin secrets panel. The flag is in the admin secrets endpoint.',
    hints: [
      'The UI hides features, but the API may still expose them. Try common admin endpoint patterns.',
      'Configuration endpoints sometimes leak internal tokens or keys.',
      'Role modification endpoints may exist even if the UI doesn\'t offer role management.',
      'Some admin operations require a special header — look for it in configuration data.',
    ],
    credentials: 'analyst / analyst2024',
    flag: 'VBANK{br0k3n_funct10n_l3v3l_4uth}',
  },
  {
    id: 3,
    title: 'Mass Assignment — Hidden Properties',
    slug: 'mass-assignment',
    appName: 'CloudPay Wallet',
    port: 9003,
    difficulty: 'Intermediate',
    category: 'Mass Assignment',
    estimatedTime: '30–40 min',
    description: 'CloudPay is a digital wallet platform that allows users to manage their profile and financial settings. The profile update API accepts JSON payloads and merges them directly into the user object without proper filtering of sensitive nested properties.',
    objective: 'Exploit the mass assignment vulnerability to increase your credit limit beyond the allowed threshold, then draw credit to reveal the flag.',
    hints: [
      'Profile update endpoints that accept JSON often merge more fields than the UI sends.',
      'Try sending nested JSON structures — the API may process properties the frontend never shows.',
      'Financial limits like credit lines may be stored as nested configuration objects.',
      'Once you modify your limits, use the credit withdrawal endpoint to trigger the flag.',
    ],
    credentials: 'user@cloudpay.io / wallet2024',
    flag: 'VBANK{m4ss_4ss1gn_h1dd3n_pr0p3rty}',
  },
  {
    id: 4,
    title: 'JWT Weak Secret Forgery',
    slug: 'jwt-forgery',
    appName: 'SecureVault API Gateway',
    port: 9004,
    difficulty: 'Intermediate',
    category: 'Broken Authentication',
    estimatedTime: '30–45 min',
    description: 'SecureVault is an API gateway that uses JSON Web Tokens for authentication and authorization. The platform issues JWTs upon login and uses them to enforce role-based access control across all endpoints.',
    objective: 'Obtain a valid JWT, discover the signing secret, forge an admin-level token, and access the restricted admin vault. The flag is in the vault response.',
    hints: [
      'JWT tokens are base64-encoded and can be decoded to inspect their payload without the secret.',
      'Common weak secrets include dictionary words, short strings, and predictable patterns.',
      'Tools like hashcat or jwt_tool can brute-force HS256 signing secrets.',
      'The admin role field in the token payload controls access to privileged endpoints.',
    ],
    credentials: 'developer / dev2024',
    flag: 'VBANK{jwt_w34k_s3cr3t_f0rg3ry}',
  },
  {
    id: 5,
    title: 'Race Condition — Double Spend',
    slug: 'race-condition',
    appName: 'QuickTransfer Payments',
    port: 9005,
    difficulty: 'Intermediate+',
    category: 'Race Condition',
    estimatedTime: '30–45 min',
    description: 'QuickTransfer is a real-time payments platform that processes fund transfers between accounts. The transfer endpoint performs balance validation before processing, but the timing window between the check and the deduction creates a critical race condition.',
    objective: 'Exploit the race condition to transfer more money than your account balance allows. The flag appears when your total outgoing transfers exceed $5,000 from a $1,000 starting balance.',
    hints: [
      'Race conditions occur when multiple requests are processed concurrently, and shared state is not properly locked.',
      'Send many transfer requests simultaneously — tools like curl, Burp Intruder, or Python threading can help.',
      'The balance check and deduction are not atomic — there is a processing delay between them.',
      'Check the recipient account balance to verify your exploit worked before looking for the flag.',
    ],
    credentials: 'sender / quick2024',
    flag: 'VBANK{r4c3_c0nd1t10n_d0ubl3_sp3nd}',
  },
  {
    id: 6,
    title: 'Business Logic — Price Manipulation',
    slug: 'business-logic',
    appName: 'ShopAPI E-Commerce',
    port: 9006,
    difficulty: 'Intermediate',
    category: 'Business Logic Flaw',
    estimatedTime: '25–40 min',
    description: 'ShopAPI is an e-commerce platform with a RESTful API for browsing products, managing a shopping cart, applying coupons, and processing checkouts. The cart and checkout logic contains fundamental business logic flaws in how it handles quantities and pricing.',
    objective: 'Manipulate the cart to checkout with a zero or negative total. The flag is revealed in the order confirmation when the total is $0 or less.',
    hints: [
      'What happens when you add items with non-positive quantities?',
      'The cart total is calculated server-side, but the calculation may not validate all inputs.',
      'Mixing positive and negative quantities for different products can produce unexpected totals.',
      'The checkout endpoint processes the order if the total is within your wallet balance.',
    ],
    credentials: 'shopper / shop2024',
    flag: 'VBANK{bus1n3ss_l0g1c_pr1c3_m4n1p}',
  },
  {
    id: 7,
    title: 'API Key Leak — Privilege Escalation',
    slug: 'api-key-leak',
    appName: 'DataStream Analytics',
    port: 9007,
    difficulty: 'Intermediate',
    category: 'Security Misconfiguration',
    estimatedTime: '25–35 min',
    description: 'DataStream is an analytics platform that provides reporting APIs for different user tiers. The platform uses API keys for internal service authentication, but debug artifacts from development may still be present in production responses.',
    objective: 'Discover the leaked internal API key and use it to access restricted internal endpoints. The flag is in the internal system endpoint.',
    hints: [
      'Always inspect HTTP response headers carefully — not just the body.',
      'Debug or internal headers are sometimes left in production deployments.',
      'Internal API keys may grant access to endpoints not documented in the public API.',
      'Try using discovered keys in different authentication headers (Authorization, X-API-Key, etc.).',
    ],
    credentials: 'viewer / view2024',
    flag: 'VBANK{4p1_k3y_l34k_pr1v_3sc}',
  },
  {
    id: 8,
    title: 'Predictable Password Reset Token',
    slug: 'predictable-token',
    appName: 'MediRecord Health Portal',
    port: 9008,
    difficulty: 'Intermediate+',
    category: 'Broken Authentication',
    estimatedTime: '35–50 min',
    description: 'MediRecord is a healthcare records portal used by medical staff. The platform implements a password reset flow using token-based verification. However, the token generation algorithm uses predictable inputs, making it possible to forge valid reset tokens.',
    objective: 'Predict the password reset token for the admin account, reset their password, log in as admin, and retrieve the flag from the admin dashboard.',
    hints: [
      'Password reset tokens generated from predictable values (timestamps, emails) are vulnerable.',
      'The server response may include timing information that helps predict the token.',
      'Common weak token generation: MD5 or SHA1 of email concatenated with a timestamp.',
      'The "Date" header in HTTP responses gives you the server\'s exact time.',
    ],
    credentials: 'nurse.jones / nurse2024',
    flag: 'VBANK{pr3d1ct4bl3_r3s3t_t0k3n}',
  },
  {
    id: 9,
    title: 'GraphQL Introspection & Auth Bypass',
    slug: 'graphql-bypass',
    appName: 'DevHub Developer Platform',
    port: 9009,
    difficulty: 'Intermediate+',
    category: 'API Abuse',
    estimatedTime: '35–50 min',
    description: 'DevHub is a developer collaboration platform that exposes a GraphQL API. Introspection is enabled in production, allowing full schema discovery. The authorization logic in certain mutations contains a subtle flaw in how it validates user roles.',
    objective: 'Use GraphQL introspection to discover hidden queries and mutations, exploit the authorization flaw to promote yourself to admin, then query the flag.',
    hints: [
      'GraphQL introspection queries (__schema, __type) reveal the entire API surface.',
      'Look for mutations that modify user roles or permissions.',
      'Authorization checks sometimes validate the wrong field — compare what\'s checked vs. what\'s used.',
      'After modifying your role, protected queries that were previously denied may become accessible.',
    ],
    credentials: 'developer / dev2024',
    flag: 'VBANK{gr4phql_1ntr0_4uth_byp4ss}',
  },
  {
    id: 10,
    title: 'Multi-Step Chained Attack',
    slug: 'chained-attack',
    appName: 'CryptoTrade Exchange',
    port: 9010,
    difficulty: 'Advanced',
    category: 'Chained Exploits',
    estimatedTime: '45–60 min',
    description: 'CryptoTrade is a cryptocurrency exchange platform with trading, notification, and administration features. The application contains multiple vulnerabilities across different components that, when chained together, allow complete compromise of the admin panel.',
    objective: 'Chain three vulnerabilities — information disclosure, SSRF, and authentication bypass — to access the admin vault. The flag is in the admin vault endpoint.',
    hints: [
      'Verbose error messages often reveal internal architecture details, including hidden endpoint paths.',
      'Webhook or notification features that accept URLs are common SSRF vectors.',
      'Internal-only endpoints (bound to localhost) may return sensitive tokens or credentials.',
      'Admin API tokens obtained via SSRF can be used to authenticate as an administrator.',
    ],
    credentials: 'trader / trade2024',
    flag: 'VBANK{ch41n3d_ssrf_t0_4dm1n_pwn}',
  },
];

module.exports = LABS;
